language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_EMULATOR_TARGET=android-22

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/android/
android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - platform-tools
    - $ANDROID_TARGET
    - $ANDROID_EMULATOR_TARGET
    - extra-android-m2repository
    - extra-android-support
    - sys-img-${ANDROID_ABI}-${ANDROID_EMULATOR_TARGET}
  licenses:
    - android-sdk-license-.+
    - '.+'

before_install:
  - yes | sdkmanager "platforms;$ANDROID_TARGET" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_EMULATOR_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  #- ./gradlew build jacocoTestReport assembleAndroidTest
  #- ./gradlew connectedCheck
  - ./gradlew assembleRelease

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false